name: Post Color of the Day
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
jobs:
  Post-Color-of-the-Day:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: yarn
      - name: Post
        run: yarn post
